name:                CoreCompilers
version:             0.1.0.0
github:              "JKTKops/CoreCompilers"
license:             BSD3
author:              "Max Kopinsky"
maintainer:          "zerglingk9012@gmail.com"
copyright:           "2019 Max Kopinsky"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Working through SPJ and DRL's "Implementing Functional Languages"
# category:            Compilers

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/JKTKops/CoreCompilers#readme>

dependencies:
- base >= 4.7 && < 5

default-extensions:
- ApplicativeDo
- GeneralizedNewtypeDeriving
- LambdaCase
- MultiParamTypeClasses
- OverloadedStrings
- TupleSections

library:
  source-dirs: src

executables:
  core-compilers:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - CoreCompilers

tests:
  core-compilers-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - CoreCompilers
